"""Historical Glottometry: core metrics + layout seriation.

Reference implementation used to validate the feasibility of a GUI tool.
Metrics follow Kalyan & François (2018), §3.2-3.3:

    kappa (cohesiveness)  k = p / (p + q)
    sigma (subgroupiness) s = eps * k

where, for a candidate subgroup G:
    p   = innovations shared by ALL members of G (outsiders may share too)
    q   = innovations that CONFLICT with G, i.e. affect some-but-not-all of G
          *and* at least one language outside G
    eps = innovations shared by exactly G and nobody else

Innovations nested strictly inside G (affecting a proper subset of G and no
outsider) are irrelevant to k and are excluded from both p and q -- see K&F
(2018: 70 fn. 9).

NA handling: the published method leaves '-' cells undefined. Every policy here
resolves an unknown to a *probability* of participation, so counts are
expectations and eps/p/q come out fractional. The default treats an NA as an
independent coin flip (P=0.5). The official Marama engine also produces
fractional values but uses a different, undocumented scheme (see README,
"Known discrepancy").

This module is the reference half of a two-implementation pair; src/core/
must agree with it to 1e-9. Fixtures are generated by tools/gen_fixtures.py.
"""

from __future__ import annotations

import numpy as np
import pandas as pd


# --------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------

def load_matrix(path: str) -> tuple[np.ndarray, list[str], list[str]]:
    """Read an innovations CSV (rows = innovations, cols = languages).

    Cells are 1 / 0 / blank / 'NA'. Returns (matrix, languages, innovations)
    with the matrix as float and unknown cells as np.nan.
    """
    df = pd.read_csv(path, index_col=0)
    return df.to_numpy(dtype=float), list(df.columns), list(df.index)


# --------------------------------------------------------------------------
# Metrics
# --------------------------------------------------------------------------

NA_POLICIES = ("half", "zero", "one", "rowMean", "colMean")


def resolve_probabilities(matrix: np.ndarray, policy: str = "half") -> np.ndarray:
    """Resolve unknown cells to participation probabilities."""
    nan = np.isnan(matrix)
    if policy == "half":
        fill = 0.5
    elif policy == "zero":
        fill = 0.0
    elif policy == "one":
        fill = 1.0
    elif policy == "rowMean":
        with np.errstate(invalid="ignore"):
            means = np.nanmean(matrix, axis=1, keepdims=True)
        fill = np.where(np.isnan(means), 0.5, means)
    elif policy == "colMean":
        with np.errstate(invalid="ignore"):
            means = np.nanmean(matrix, axis=0, keepdims=True)
        fill = np.where(np.isnan(means), 0.5, means)
    else:
        raise ValueError(f"unknown NA policy: {policy!r}")
    return np.where(nan, fill, matrix)


class Glottometry:
    """Computes kappa/sigma for every attested subgroup of a dataset."""

    def __init__(self, matrix: np.ndarray, languages: list[str],
                 na_policy: str = "half"):
        self.M = matrix
        self.languages = languages
        self.na_policy = na_policy
        self.n_inn, self.n_lang = matrix.shape
        self.p1 = resolve_probabilities(matrix, na_policy)
        self.p0 = 1.0 - self.p1

    def stats(self, mask: np.ndarray) -> dict[str, float]:
        """Return eps/kappa/sigma/p/q for the subgroup given by a boolean mask."""
        p1_in, p0_in, p0_out = self.p1[:, mask], self.p0[:, mask], self.p0[:, ~mask]

        all_in = p1_in.prod(1)          # P(every member participated)
        none_in = p0_in.prod(1)         # P(no member participated)
        none_out = p0_out.prod(1)       # P(no outsider participated)

        eps = float((all_in * none_out).sum())
        p = float(all_in.sum())
        # some-but-not-all of G, together with at least one outsider
        q = float(((1.0 - all_in - none_in) * (1.0 - none_out)).sum())

        kappa = p / (p + q) if (p + q) else 0.0
        return {"epsilon": eps, "kappa": kappa, "sigma": eps * kappa, "p": p, "q": q}

    def candidates(self) -> np.ndarray:
        """Distinct attested innovation patterns, as a boolean array.

        This is the key to tractability: a subgroup needs eps >= 1 to count as
        attested (K&F 2018: 80), so candidates are bounded by the number of
        *distinct rows*, never by 2**n_lang.

        The set of ALL languages is excluded: the family as a whole is not a
        subgroup of itself, nothing can conflict with it, so its kappa is a
        trivial 1. The Marama engine omits it too.
        """
        hard = np.where(np.isnan(self.M), 0, self.M).astype(bool)
        pats = np.unique(hard, axis=0)
        return pats[(pats.sum(1) >= 2) & (pats.sum(1) < self.n_lang)]

    def subgroups(self, min_sigma: float = 0.0,
                  min_epsilon: float = 1.0) -> pd.DataFrame:
        """Score every attested subgroup; return a DataFrame sorted by sigma.

        `min_epsilon` defaults to 1 because K&F (2018: 80) require a subgroup to
        "have at least one exclusively shared innovation". With integer data
        that is the same as eps > 0, but once NA weighting makes eps fractional
        the two diverge, and eps > 0 admits groups with only partial evidence.
        """
        rows = []
        for mask in self.candidates():
            s = self.stats(mask)
            if s["epsilon"] >= min_epsilon and s["sigma"] >= min_sigma:
                members = [l for l, m in zip(self.languages, mask) if m]
                rows.append({**s, "size": len(members), "members": members,
                             "mask": mask})
        return (pd.DataFrame(rows)
                .sort_values("sigma", ascending=False)
                .reset_index(drop=True))


# --------------------------------------------------------------------------
# Layout: find a 1-D ordering that makes displayed subgroups contiguous
# --------------------------------------------------------------------------

def _breaks(order: np.ndarray, mask: np.ndarray) -> int:
    """Gaps in a subgroup when its members are read along `order` (0 = contiguous)."""
    idx = np.flatnonzero(mask[order])
    return int((np.diff(idx) > 1).sum())


def seriate(masks: list[np.ndarray], weights: list[float], n_lang: int,
            restarts: int = 20, iters: int = 6000, seed: int = 0):
    """Simulated-annealing search for an ordering minimising weighted breaks.

    Returns (order, cost). Cost 0 means every subgroup is a contiguous run and
    can be drawn as a simple capsule, exactly like K&F's published figure.
    """
    rng = np.random.default_rng(seed)

    def cost(order):
        return sum(w * _breaks(order, m) for w, m in zip(weights, masks))

    best, best_cost = None, np.inf
    for _ in range(restarts):
        order = rng.permutation(n_lang)
        cur = cost(order)
        temp = 5.0
        for _ in range(iters):
            temp *= 0.9993
            i, j = rng.integers(0, n_lang, 2)
            if i == j:
                continue
            cand = order.copy()
            if rng.random() < 0.5:
                cand[i], cand[j] = cand[j], cand[i]
            else:  # segment reversal
                a, b = sorted((i, j))
                cand[a:b + 1] = cand[a:b + 1][::-1]
            cc = cost(cand)
            if cc <= cur or rng.random() < np.exp((cur - cc) / max(temp, 1e-9)):
                order, cur = cand, cc
        if cur < best_cost:
            best, best_cost = order, cur
    return best, best_cost


# --------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    path = sys.argv[1] if len(sys.argv) > 1 else "data/innov.csv"

    M, langs, inns = load_matrix(path)
    print(f"{len(inns)} innovations x {len(langs)} languages "
          f"({int(np.isnan(M).sum())} NA cells)")

    g = Glottometry(M, langs)
    df = g.subgroups()
    print(f"{len(df)} attested subgroups\n")

    print(f"{'sigma':>7} {'kappa':>6} {'eps':>6}  members")
    for _, r in df.head(12).iterrows():
        print(f"{r.sigma:7.2f} {r.kappa:6.2f} {r.epsilon:6.2f}  {'+'.join(r.members)}")

    shown = df[df.sigma >= 1.0]
    order, cost = seriate(list(shown['mask']), list(shown.sigma), len(langs))
    contiguous = sum(1 for m in shown['mask'] if _breaks(order, m) == 0)
    print(f"\nlayout: {contiguous}/{len(shown)} of the sigma>=1 subgroups are "
          f"contiguous (weighted break cost {cost:.2f})")
    print("order:", " ".join(langs[i] for i in order))
